#Config for CivGuide
#Example
#------------
#PluginName:
#  CustomEventName:
#    events:
#      - ActualBukkitEvent
#      - ActualBukkitEvent
#    text: Text to display
#  RegularBukkitEvent:
#    text: text to display
PrisonPearl:
  PearlPickupEvent:
    events:
      - InventoryClickEvent
      - PlayerPickupItemEvent
    trigger:
      material: ENDER_PEARL
    text: When you kill another player while holding a pearl, that player will be imprisoned in the end until released. Pearls must be stored in a container with coal or they will be freed when the server restarts.
  PrisonPearlEvent:
    text: When a player is pearled they will be trapped in the end until they're freed. If you're pearled, you can use the command /ppl to get the location of your pearl in the overworld.
  KilledPlayer:
    events:
      - EntityDeathEvent
    text: When you kill another player while holding a pearl, that player will be imprisoned in the end until released. Pearls must be stored in a container with coal or they will be freed when the server restarts.
Citadel:
  url: https://github.com/civcraft/citadel/wiki
  ReinforcementDamageEvent:
    text: Blocks can be reinforced with stone, iron, and diamond. Reinforced blocks need to be broken multiple times before they will break for good. If you reinforce a something that can be opened such as a door or chest it will only be accessible to the people on your NameLayer group
  BlockPlaceEvent:
    text: When you place blocks, you can reinforce them with stone, iron, or diamond by doing the command /ctr and clicking the block with any of those items. Reinforced blocks need to be broken multiple times before the block will actually break. If you reinforce a something that can be opened such as a door or chest it will only be accessible to the people on your NameLayer group
  GetReinforcementMaterial:
    event:
      - PlayerPickupItemEvent
      - InventoryClickEvent
    trigger:
      material: DIAMOND|IRON_INGOT|STONE
      duras:
        - 0
        - 1
    text: When you place blocks, you can reinforce them with stone, iron, or diamond by doing the command /ctr and clicking the block with any of those items. Reinforced blocks need to be broken multiple times before the block will actually break. If you reinforce a something that can be opened such as a door or chest it will only be accessible to the people on your NameLayer group
FactoryMod:
  url: https://github.com/civcraft/factorymod/wiki
  PlayerInteractEvent:
    text: Factories are special structures consisting of a chest, crafting table, and furnace in that order. Factories allow for more efficient production of goods with a greater initial investment. See the factorymod wiki for more info.
  GetCompactedItem:
    events:
      - PlayerPickupEvent
      - InventoryClickEvent
    trigger:
      material: '.*'
      lore:
        - Compacted Item
    text: You have picked up a compacted item. Items can be compacted in a special factory with special items called crates. Compacted items represent a full stack of the item.
ItemExchange:
  url: https://github.com/civcraft/itemexchange/wiki
  PlayerInteractEvent:
    text: ItemExchange is a plugin for creating shops. When interacting with shop chests, punch them with a fist to switch exchanged. Once you're on the desired exchange, hit the chest with the input item. To create a shop, see the item exchange wiki.
RealisticBiomes:
  url: https://github.com/civcraft/realisticbiomes/wiki
  PlayerInteractEvent:
    text: RealisticBiomes is a plugin to limit plant growth. Hit the ground with a crop, or right click a crop with a stick to see how long it will take to grow, and how far along it is. Most crops are persistant, taking a set amount of time to grow based on where it's planted.
ArthropodEgg:
  url: http://biggestnerd.com
  GetBainSword:
    events:
      - PlayerPickupItemEvent
      - InventoryClickEvent
    trigger:
      material: '.*_SWORD'
      enchants:
        - DAMAGE_ARTHROPODS
    text: When you kill a neutral, adult animal with a bane of arthropods sword, there is a chance the animal will drop a spawn egg rather than it's normal drops. The chance is increased based on the level of bane as well as any looting enchantments.
  GetSpawnEgg:
    events:
      - PlayerPickupItemEvent
      - InventoryClickEvent
    trigger:
      material: MONSTER_EGG
      duras:
        - 65
        - 90
        - 91
        - 92
        - 93
        - 94
        - 95
        - 98
        - 96
        - 100
        - 101
        - 120
      text: When you kill a neutral, adult animal with a bane of arthropods sword, there is a chance the animal will drop a spawn egg rather than it's normal drops. The chance is increased based on the level of bane as well as any looting enchantments.
CombatTagPlus:
  PlayerCombatTagEvent:
    text: When a player hits another player, both players are combat tagged for 30 seconds. When a player is combat tagged the timer is refreshed every time they hit or get hit. You are also combat tagged when throwing ender pearls. If you log out while combat tagged you will leave an npc that can be killed.
CivPets:
  EntityTameEvent:
    text: Animals can be untamed by right clicking them with cookies. Untamed animals can then be re-tamed like normal.
MusterCull:
  BreedEntity:
    events:
      - PlayerInteractEntityEvent
    text: Mustercull is a plugin to limit mob spawning in an effort to reduce lag. If there are a lot of entities in one area as well as a lot of server lag MusterCull will begin killing the mobs. Try to kill animals as you breed them to prevent your farms from being culled.
Random-Spawn:
  PlayerRespawnEvent:
    text: Random-Spawn is a plugin to randomly spawn players. Rather than spawning at a set spawn area, you will spawn in a random location when you die. You can set your bed like normal to spawn in the same place every time.
BetterShards:
  url: https://github.com/Civcraft/BetterShards/wiki/Features
  PlayerArrivedChangeServerEvent:
    text: You have just switched shards. More info on bettershards here
JukeAlert:
  GetSnitchBlock:
    events:
      - InventoryClickEvent
      - PlayerPickupItemEvent
    trigger: 
      material: JUKEBOX|NOTE_BLOCK
    text: When you place a jukebox or noteblock and reinforce it on a group it becomes a snitch. Snitches have a field 23x23x23 blocks centered on the snitch. If a player not on the snitch's group enters the field, everyone on the group will be sent a message notifying them of the entry. Jukebox snitches also log when players break blocks, open chests, etc within their field. You can check Jukebox logs with the command /jainfo when standing near your snitch

sql:
  dbname: minecraft
  host: localhost
  pass: root
  port: 3306
  user: root

#Books below!
#Reference names for each book, if you don't put the book name here it won't be loaded
booklist: 
  - "welcome"
  - "ham"

# A book can have 256 characters per page w/ 50 pages max.
books:
  welcome:
    fullname: "Welcome to CivCraft"
    pages:
      - "   ~c:r~iWhat is Civraft?~n~r~qCivCraft is an experiment for communities & political ideologies [...] to work together to create and shape civilization or to watch it fall~q~n-Ttk2, server owner"
      - "   ~iWhat is Civraft?~n~bNOT just survivial:~n~rAdmins are hands-off and only handle glitches and hackers.~n~bNOT just chaos:~n~rMods allow players and towns to enforce their own rules.~n~bNOT just foreplay;)~n~rNobody pretends -- conflict is genuine and heated."
      - "   ~iBasic Mechanics~n~r-The world is a circle~n-Stretches 15k blocks~n-500 block chat range~n-Respawn in random area unless you sleep~n-Food grows slowly~n-Mobs spawn sparsely~n-No Nether portals is a lie~n-Nether biomes also~n-No XP from killing"
      - " Ect. Ect. Ect.~n The welcome to civcraft book needs to be updated anyways, nose goes."
  ham:
    fullname: "Green Eggs & Ham"
    pages:
      - "~iI do not like ~c:grgreen ~c:beggs and ham..."
      - "~iI do not like them.."
      - "~i~u~c:rSam~c:b-~c:dgI~c:b-~c:gAm."

# Page code reference:
#-----------------------
# ~n - New Line
# ~q - Insert Quotation "
# ~s - Strikethrough
# ~b - Bold
# ~i - Italic
# ~u - Underline
# ~r - Reset/remove formatting
# -- Coloring:
# ~c:m - Magic
# ~c:a - Aqua
# ~c:b - Black
# ~c:bl - Blue
# ~c:da - Dark Aqua
# ~c:db - Dark Blue
# ~c:dg - Dark Grey
# ~c:dgr - Dark Green
# ~c:dp - Dark Purple
# ~c:dr - Dark Red
# ~c:go - Gold
# ~c:g - Gray
# ~c:gr - Green
# ~c:lp - Light Purple
# ~c:r - Red
# ~c:w - White
# ~c:y - Yellow
#-----------------------