name: CivGuide
author: biggestnerd
version: 1.2.1
main: com.biggestnerd.civguide.CivGuide
depend: [NameLayer, CivMenu]
softdepend: [Citadel,ArthropodEgg,CombatTagPlus,ItemExchange,FactoryMod,PrisonPearl,RealisticBiomes,CivPets,MusterCull,Random-Spawn,AFKPGC]
commands:
  dismiss:
    description: "Permanently dismiss the guide for a specific event"
    usage: "Usage: /dismiss <eventname>"
  guide:
    description: "Gives the player the designated guide"
    usage: "Usage: /guide <guidename>"
permissions:
  civguide.dismiss:
    description: "Allow players to dismiss guide events"
    default: true